import '@/assets/styles/globals.css'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    keywords:"demo,practice,example,try,rough",
  };

const MainLayout = ({children}) => {
    return (
        <html>
      
            <body>
                {children}
            </body>
        </html>
    )
}

export default MainLayout
